# Конфигурация сборки
[build]
  command = "npm run build"
  # Директория, соответствующая outDir в vite.config.ts
  publish = "dist"
  base = "."

[build.environment]
  NODE_VERSION = "16"

# Настройка маршрутизации для SPA
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
